<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProductVersion>8.0.30703</ProductVersion>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{B8E3CE5C-63AF-4FEB-B34A-404827F7E406}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>Framework_SW2013</RootNamespace>
    <AssemblyName>Framework_SW2013</AssemblyName>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;SW2011 SW2012</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <RegisterForComInterop>false</RegisterForComInterop>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>SW2011 SW2012</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <RegisterForComInterop>false</RegisterForComInterop>
  </PropertyGroup>
  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
  </PropertyGroup>
  <PropertyGroup>
    <AssemblyOriginatorKeyFile>Etienne.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp">
      <EmbedInteropTypes>False</EmbedInteropTypes>
    </Reference>
    <Reference Include="SolidWorks.Interop.sldworks">
      <HintPath>..\..\..\..\..\..\Program Files\SolidWorks Corp\SolidWorks\api\redist\SolidWorks.Interop.sldworks.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
    <Reference Include="SolidWorks.Interop.swconst">
      <HintPath>..\..\..\..\..\..\Program Files\SolidWorks Corp\SolidWorks\api\redist\SolidWorks.Interop.swconst.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
      <Private>False</Private>
    </Reference>
    <Reference Include="SolidWorks.Interop.swpublished">
      <HintPath>..\..\..\..\..\..\Program Files\SolidWorks Corp\SolidWorks\api\redist\SolidWorks.Interop.swpublished.dll</HintPath>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </Reference>
    <Reference Include="System">
      <EmbedInteropTypes>False</EmbedInteropTypes>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Windows.Forms">
      <EmbedInteropTypes>False</EmbedInteropTypes>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Include="eObjet.cs" />
    <Compile Include="eGestDeProprietes.cs" />
    <Compile Include="DlgSauverUnFichier.cs" />
    <Compile Include="DlgRechercherUnFichier.cs" />
    <Compile Include="eLog.cs" />
    <Compile Include="eGestDeSelection.cs" />
    <Compile Include="eFichierSW.cs" />
    <Compile Include="eGeometrie.cs" />
    <Compile Include="DlgRechercherUnDossier.cs" />
    <Compile Include="eDimensionVue.cs" />
    <Compile Include="eVue.cs" />
    <Compile Include="eFeuille.cs" />
    <Compile Include="ePropriete.cs" />
    <Compile Include="eFonction.cs" />
    <Compile Include="eCorps.cs" />
    <Compile Include="eDossier.cs" />
    <Compile Include="eAssemblage.cs" />
    <Compile Include="eConfiguration.cs" />
    <Compile Include="eComposant.cs" />
    <Compile Include="eDessin.cs" />
    <Compile Include="ePiece.cs" />
    <Compile Include="intChaine.cs" />
    <Compile Include="intDebug.cs" />
    <Compile Include="Constantes.cs" />
    <Compile Include="eModele.cs" />
    <Compile Include="eSldWorks.cs" />
    <Compile Include="eRecherche.cs" />
    <Compile Include="eGestDeConfigurations.cs" />
    <Compile Include="eGestOptions.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Etienne.snk" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <!-- To modify your build process, add your task inside one of the targets below and uncomment it. 
       Other similar extension points exist, see Microsoft.Common.targets.
  <Target Name="BeforeBuild">
  </Target>
  <Target Name="AfterBuild">
  </Target>
  -->
</Project>